### ISSUE TITLE
你好，我使用你的efi作为基础解决了蓝牙问题

### ISSUE THREAD

**Issue by SunSgr** [Ghost-Cavendish/Hackintosh_for_R7000P_2021A_5800H#1]
这是我的efi部分（由于GitHub上传文件限制，我仅仅把修改的部分打包了），反馈给你，同时谢谢你提供的efi
[OC.zip](https://github.com/Ghost-Cavendish/Hackintosh_for_R7000P_2021A_5800H/files/12294682/OC.zip)

**Comment by Ghost-Cavendish** [comment]
加个微信老哥

**Comment by Ghost-Cavendish** [comment]
怎么弄好的呀

**Comment by Ghost-Cavendish** [comment]
hdbdbjjdvrj我的微信

**Comment by Ghost-Cavendish** [comment]
我用你的efi，蓝牙只能搜索到设备，不能正常使用你能正常使用吗，你的系统是macos sonoma不
